<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterOptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('master_options')->insert([
            ['kode' => 'ADMIN', 'deskripsi' => 'Administrator', 'tipe' => 'USERTYPE', 'created_by' => 1, 'updated_by' => 1],
            ['kode' => 'ADM', 'deskripsi' => 'Admin', 'tipe' => 'USERTYPE', 'created_by' => 1, 'updated_by' => 1],
            ['kode' => 'OPR', 'deskripsi' => 'Operator', 'tipe' => 'USERTYPE', 'created_by' => 1, 'updated_by' => 1]
        ]);

        DB::table('master_options')->insert([["kode" => "AD", "deskripsi" => "Andorra", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AE", "deskripsi" => "Utd.Arab Emir.", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AF", "deskripsi" => "Afghanistan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AG", "deskripsi" => "Antigua/Barbuda", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AI", "deskripsi" => "Anguilla", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AL", "deskripsi" => "Albania", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AM", "deskripsi" => "Armenia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AN", "deskripsi" => "Dutch Antilles", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AO", "deskripsi" => "Angola", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AQ", "deskripsi" => "Antarctica", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AR", "deskripsi" => "Argentina", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AS", "deskripsi" => "Samoa, America", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AT", "deskripsi" => "Austria", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AU", "deskripsi" => "Australia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AW", "deskripsi" => "Aruba", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "AZ", "deskripsi" => "Azerbaijan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BA", "deskripsi" => "Bosnia-Herz.", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BB", "deskripsi" => "Barbados", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BD", "deskripsi" => "Bangladesh", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BE", "deskripsi" => "Belgium", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BF", "deskripsi" => "Burkina Faso", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BG", "deskripsi" => "Bulgaria", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BH", "deskripsi" => "Bahrain", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BI", "deskripsi" => "Burundi", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BJ", "deskripsi" => "Benin", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BL", "deskripsi" => "Blue", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BM", "deskripsi" => "Bermuda", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BN", "deskripsi" => "Brunei Daruss.", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BO", "deskripsi" => "Bolivia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BR", "deskripsi" => "Brazil", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BS", "deskripsi" => "Bahamas", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BT", "deskripsi" => "Bhutan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BV", "deskripsi" => "Bouvet Islands", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BW", "deskripsi" => "Botswana", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BY", "deskripsi" => "Belarus", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "BZ", "deskripsi" => "Belize", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CA", "deskripsi" => "Canada", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CC", "deskripsi" => "Coconut Islands", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CD", "deskripsi" => "Dem. Rep. Congo", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CF", "deskripsi" => "CAR", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CG", "deskripsi" => "Rep.of Congo", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CH", "deskripsi" => "Switzerland", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CI", "deskripsi" => "Cote d'Ivoire", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CK", "deskripsi" => "Cook Islands", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CL", "deskripsi" => "Chile", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CM", "deskripsi" => "Cameroon", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CN", "deskripsi" => "China", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CO", "deskripsi" => "Colombia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CR", "deskripsi" => "Costa Rica", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CS", "deskripsi" => "Serbia/Monten.", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CU", "deskripsi" => "Cuba", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CV", "deskripsi" => "Cape Verde", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CX", "deskripsi" => "Christmas Islnd", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CY", "deskripsi" => "Cyprus", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "CZ", "deskripsi" => "Czech Republic", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "DE", "deskripsi" => "Germany", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "DJ", "deskripsi" => "Djibouti", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "DK", "deskripsi" => "Denmark", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "DM", "deskripsi" => "Dominica", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "DO", "deskripsi" => "Dominican Rep.", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "DZ", "deskripsi" => "Algeria", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "EC", "deskripsi" => "Ecuador", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "EE", "deskripsi" => "Estonia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "EG", "deskripsi" => "Egypt", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "EH", "deskripsi" => "West Sahara", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "ER", "deskripsi" => "Eritrea", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "ES", "deskripsi" => "Spain", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "ET", "deskripsi" => "Ethiopia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "EU", "deskripsi" => "European Union", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "FI", "deskripsi" => "Finland", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "FJ", "deskripsi" => "Fiji", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "FK", "deskripsi" => "Falkland Islnds", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "FM", "deskripsi" => "Micronesia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "FO", "deskripsi" => "Faroe Islands", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "FR", "deskripsi" => "France", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GA", "deskripsi" => "Gabon", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GB", "deskripsi" => "United Kingdom", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GD", "deskripsi" => "Grenada", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GE", "deskripsi" => "Georgia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GF", "deskripsi" => "French Guayana", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GH", "deskripsi" => "Ghana", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GI", "deskripsi" => "Gibraltar", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GL", "deskripsi" => "Greenland", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GM", "deskripsi" => "Gambia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GN", "deskripsi" => "Guinea", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GP", "deskripsi" => "Guadeloupe", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GQ", "deskripsi" => "Equatorial Guin", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GR", "deskripsi" => "Greece", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GS", "deskripsi" => "S. Sandwich Ins", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GT", "deskripsi" => "Guatemala", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GU", "deskripsi" => "Guam", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GW", "deskripsi" => "Guinea-Bissau", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "GY", "deskripsi" => "Guyana", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "HK", "deskripsi" => "Hong Kong", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "HM", "deskripsi" => "Heard/McDon.Isl", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "HN", "deskripsi" => "Honduras", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "HR", "deskripsi" => "Croatia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "HT", "deskripsi" => "Haiti", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "HU", "deskripsi" => "Hungary", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "ID", "deskripsi" => "Indonesia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "IE", "deskripsi" => "Ireland", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "IL", "deskripsi" => "Israel", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "IN", "deskripsi" => "India", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "IO", "deskripsi" => "Brit.Ind.Oc.Ter", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "IQ", "deskripsi" => "Iraq", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "IR", "deskripsi" => "Iran", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "IS", "deskripsi" => "Iceland", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "IT", "deskripsi" => "Italy", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "JM", "deskripsi" => "Jamaica", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "JO", "deskripsi" => "Jordan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "JP", "deskripsi" => "Japan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "KE", "deskripsi" => "Kenya", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "KG", "deskripsi" => "Kyrgyzstan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "KH", "deskripsi" => "Cambodia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "KI", "deskripsi" => "Kiribati", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "KM", "deskripsi" => "Comoros", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "KN", "deskripsi" => "St Kitts&Nevis", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "KP", "deskripsi" => "North Korea", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "KR", "deskripsi" => "South Korea", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "KW", "deskripsi" => "Kuwait", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "KY", "deskripsi" => "Cayman Islands", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "KZ", "deskripsi" => "Kazakhstan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "LA", "deskripsi" => "Laos", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "LB", "deskripsi" => "Lebanon", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "LC", "deskripsi" => "St. Lucia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "LI", "deskripsi" => "Liechtenstein", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "LK", "deskripsi" => "Sri Lanka", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "LR", "deskripsi" => "Liberia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "LS", "deskripsi" => "Lesotho", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "LT", "deskripsi" => "Lithuania", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "LU", "deskripsi" => "Luxembourg", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "LV", "deskripsi" => "Latvia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "LY", "deskripsi" => "Libya", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MA", "deskripsi" => "Morocco", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MC", "deskripsi" => "Monaco", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MD", "deskripsi" => "Moldova", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MG", "deskripsi" => "Madagascar", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MH", "deskripsi" => "Marshall Islnds", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MK", "deskripsi" => "Macedonia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "ML", "deskripsi" => "Mali", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MM", "deskripsi" => "Burma", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MN", "deskripsi" => "Mongolia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MO", "deskripsi" => "Macau", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MP", "deskripsi" => "N.Mariana Islnd", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MQ", "deskripsi" => "Martinique", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MR", "deskripsi" => "Mauretania", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MS", "deskripsi" => "Montserrat", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MT", "deskripsi" => "Malta", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MU", "deskripsi" => "Mauritius", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MV", "deskripsi" => "Maldives", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MW", "deskripsi" => "Malawi", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MX", "deskripsi" => "Mexico", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MY", "deskripsi" => "Malaysia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "MZ", "deskripsi" => "Mozambique", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NA", "deskripsi" => "Namibia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NC", "deskripsi" => "New Caledonia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NE", "deskripsi" => "Niger", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NF", "deskripsi" => "Norfolk Islands", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NG", "deskripsi" => "Nigeria", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NI", "deskripsi" => "Nicaragua", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NL", "deskripsi" => "Netherlands", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NO", "deskripsi" => "Norway", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NP", "deskripsi" => "Nepal", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NR", "deskripsi" => "Nauru", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NT", "deskripsi" => "NATO", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NU", "deskripsi" => "Niue", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "NZ", "deskripsi" => "New Zealand", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "OM", "deskripsi" => "Oman", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "OR", "deskripsi" => "Orange", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PA", "deskripsi" => "Panama", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PE", "deskripsi" => "Peru", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PF", "deskripsi" => "Frenc.Polynesia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PG", "deskripsi" => "Pap. New Guinea", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PH", "deskripsi" => "Philippines", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PK", "deskripsi" => "Pakistan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PL", "deskripsi" => "Poland", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PM", "deskripsi" => "St.Pier,Miquel.", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PN", "deskripsi" => "Pitcairn Islnds", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PR", "deskripsi" => "Puerto Rico", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PS", "deskripsi" => "Palestine", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PT", "deskripsi" => "Portugal", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PW", "deskripsi" => "Palau", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "PY", "deskripsi" => "Paraguay", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "QA", "deskripsi" => "Qatar", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "RE", "deskripsi" => "Reunion", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "RO", "deskripsi" => "Romania", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "RU", "deskripsi" => "Russian Fed.", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "RW", "deskripsi" => "Rwanda", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SA", "deskripsi" => "Saudi Arabia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SB", "deskripsi" => "Solomon Islands", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SC", "deskripsi" => "Seychelles", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SD", "deskripsi" => "Sudan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SE", "deskripsi" => "Sweden", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SG", "deskripsi" => "Singapore", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SH", "deskripsi" => "Saint Helena", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SI", "deskripsi" => "Slovenia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SJ", "deskripsi" => "Svalbard", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SK", "deskripsi" => "Slovakia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SL", "deskripsi" => "Sierra Leone", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SM", "deskripsi" => "San Marino", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SN", "deskripsi" => "Senegal", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SO", "deskripsi" => "Somalia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SR", "deskripsi" => "Suriname", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "ST", "deskripsi" => "S.Tome,Principe", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SV", "deskripsi" => "El Salvador", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SY", "deskripsi" => "Syria", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "SZ", "deskripsi" => "Swaziland", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TC", "deskripsi" => "Turksh Caicosin", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TD", "deskripsi" => "Chad", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TF", "deskripsi" => "French S.Territ", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TG", "deskripsi" => "Togo", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TH", "deskripsi" => "Thailand", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TJ", "deskripsi" => "Tajikistan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TK", "deskripsi" => "Tokelau Islands", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TL", "deskripsi" => "East Timor", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TM", "deskripsi" => "Turkmenistan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TN", "deskripsi" => "Tunisia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TO", "deskripsi" => "Tonga", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TP", "deskripsi" => "East Timor", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TR", "deskripsi" => "Turkey", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TT", "deskripsi" => "Trinidad,Tobago", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TV", "deskripsi" => "Tuvalu", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TW", "deskripsi" => "Taiwan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "TZ", "deskripsi" => "Tanzania", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "UA", "deskripsi" => "Ukraine", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "UG", "deskripsi" => "Uganda", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "UM", "deskripsi" => "Minor Outl.Isl.", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "UN", "deskripsi" => "United Nations", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "US", "deskripsi" => "USA", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "UY", "deskripsi" => "Uruguay", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "UZ", "deskripsi" => "Uzbekistan", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "VA", "deskripsi" => "Vatican City", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "VC", "deskripsi" => "St. Vincent", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "VE", "deskripsi" => "Venezuela", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "VG", "deskripsi" => "Brit.Virgin Is.", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "VI", "deskripsi" => "Amer.Virgin Is.", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "VN", "deskripsi" => "Vietnam", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "VU", "deskripsi" => "Vanuatu", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "WF", "deskripsi" => "Wallis,Futuna", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "WS", "deskripsi" => "Samoa", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "YE", "deskripsi" => "Yemen", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "YT", "deskripsi" => "Mayotte", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "ZA", "deskripsi" => "South Africa", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "ZM", "deskripsi" => "Zambia", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1],
        ["kode" => "ZW", "deskripsi" => "Zimbabwe", "tipe" => "COUNTRY", "created_by" => 1, "updated_by" => 1]
        ]);

        DB::table('master_options')->insert([
            ["kode" => "ZA01", "deskripsi" => "AG-IJ Reguler Customer", "tipe" => "ACCGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ZA02", "deskripsi" => "AG-IJ One-Time Customer", "tipe" => "ACCGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ZA03", "deskripsi" => "AG-IJ Ship-to Party", "tipe" => "ACCGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ZA04", "deskripsi" => "AG-IJ Bill-to Party", "tipe" => "ACCGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ZA05", "deskripsi" => "AG-IJ Tax-to Party", "tipe" => "ACCGROUP", "created_by" => 1, "updated_by" => 1]
        ]);

        DB::table('master_options')->insert([
            ["kode" => "1010", "deskripsi" => "Raw Material", "tipe" => "MRPGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "1020", "deskripsi" => "Chemicals", "tipe" => "MRPGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "1030", "deskripsi" => "Packaging", "tipe" => "MRPGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "1040", "deskripsi" => "Spareparts", "tipe" => "MRPGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "1050", "deskripsi" => "Accessories", "tipe" => "MRPGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "1060", "deskripsi" => "Tools", "tipe" => "MRPGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "1310", "deskripsi" => "Knitting", "tipe" => "MRPGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "1320", "deskripsi" => "Dyeing", "tipe" => "MRPGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "1330", "deskripsi" => "Finishing", "tipe" => "MRPGROUP", "created_by" => 1, "updated_by" => 1]
        ]);

        DB::table('master_options')->insert([
            ["kode" => "ABF", "deskripsi" => "Waste", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CH00", "deskripsi" => "CH Contract Handling", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CONT", "deskripsi" => "Kanban Container", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "COUP", "deskripsi" => "Coupons", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "DIEN", "deskripsi" => "Service", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "EPA", "deskripsi" => "Equipment Package", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ERSA", "deskripsi" => "Spare Parts", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "FERT", "deskripsi" => "Finished Product", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "FGTR", "deskripsi" => "Beverages", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "FHMI", "deskripsi" => "Production Resource/Tool", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "FOOD", "deskripsi" => "Foods (excl. perishables)", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "FRIP", "deskripsi" => "Perishables", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "HALB", "deskripsi" => "Semifinished Product", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "HAWA", "deskripsi" => "Trading Goods", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "HERS", "deskripsi" => "Manufacturer Part", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "HIBE", "deskripsi" => "Operating supplies", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "IBAU", "deskripsi" => "Maintenance assemblies", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "INTR", "deskripsi" => "Intra materials", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KMAT", "deskripsi" => "Configurable materials", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "LEER", "deskripsi" => "Empties", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "LEIH", "deskripsi" => "Returnable packaging", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "LGUT", "deskripsi" => "Empties (retail)", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MODE", "deskripsi" => "Apparel (seasonal)", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MPO", "deskripsi" => "Material Planning Object", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "NLAG", "deskripsi" => "Non-stock materials", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "NOF1", "deskripsi" => "Nonfoods", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PIPE", "deskripsi" => "Pipeline materials", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PLAN", "deskripsi" => "Trading goods (planned)", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PROC", "deskripsi" => "Process materials", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PROD", "deskripsi" => "Product groups", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ROH", "deskripsi" => "Raw materials", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "UNBW", "deskripsi" => "Nonvaluated materials", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "VERP", "deskripsi" => "Packaging", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "VKHM", "deskripsi" => "Additionals", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "VOLL", "deskripsi" => "Full products", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "WERB", "deskripsi" => "Product catalogs", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "WERT", "deskripsi" => "Value-only materials", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "WETT", "deskripsi" => "Competitor products", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ZFGD", "deskripsi" => "Discontinued FG", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ZKG", "deskripsi" => "Material Kiloan", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ZNTR", "deskripsi" => "Non Value Materials", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ZPRM", "deskripsi" => "Promotion Materials", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ZSPM", "deskripsi" => "Supporting Material", "tipe" => "MATTYPE", "created_by" => 1, "updated_by" => 1]
        ]);

        DB::table('master_options')->insert([
            ["kode" => "ACR", "deskripsi" => "Acre", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "AU", "deskripsi" => "Activity unit", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "BAG", "deskripsi" => "Bag", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "BAL", "deskripsi" => "Bale", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "BOX", "deskripsi" => "BOX", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "BT", "deskripsi" => "Bottle", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "C3S", "deskripsi" => "Cubic centimeter/second", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CAN", "deskripsi" => "Canister", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CAR", "deskripsi" => "Carton", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CCM", "deskripsi" => "Cubic centimeter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CD3", "deskripsi" => "Cubic decimeter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CL", "deskripsi" => "Centiliter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CM", "deskripsi" => "Centimeter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CM2", "deskripsi" => "Square centimeter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CMS", "deskripsi" => "Centimeter/second", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CNS", "deskripsi" => "CONES", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CRT", "deskripsi" => "Crate", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "CV", "deskripsi" => "Case", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "D", "deskripsi" => "Days", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "DAY", "deskripsi" => "Days", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "DEG", "deskripsi" => "Degree", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "DM", "deskripsi" => "Decimeter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "DR", "deskripsi" => "Drum", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "DZ", "deskripsi" => "Dozen", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "EA", "deskripsi" => "each", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "EML", "deskripsi" => "Enzyme Units / Milliliter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "EU", "deskripsi" => "Enzyme Units", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "FOZ", "deskripsi" => "Fluid Ounce US", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "FT", "deskripsi" => "Foot", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "FT2", "deskripsi" => "Square foot", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "FT3", "deskripsi" => "Cubic foot", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "G", "deskripsi" => "Gram", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "G/L", "deskripsi" => "gram act.ingrd / liter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "GAI", "deskripsi" => "Gram act. ingrd.", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "GAL", "deskripsi" => "US gallon", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "GAU", "deskripsi" => "Gram Gold", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "GJ", "deskripsi" => "Gigajoule", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "GLI", "deskripsi" => "Gram/liter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "GM", "deskripsi" => "Gram/Mol", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "GM2", "deskripsi" => "Gram/square meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "GM3", "deskripsi" => "Gram/Cubic meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "GOH", "deskripsi" => "Gigaohm", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "GPH", "deskripsi" => "Gallons per hour (US)", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "GPM", "deskripsi" => "Gallons per mile (US)", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "GRO", "deskripsi" => "Gross", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "H", "deskripsi" => "Hour", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "HA", "deskripsi" => "Hectare", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "HL", "deskripsi" => "Hectoliter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "HR", "deskripsi" => "Hours", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "IB", "deskripsi" => "Pikofarad", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "JKG", "deskripsi" => "Joule/Kilogram", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "JKK", "deskripsi" => "Spec. Heat Capacity", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "JMO", "deskripsi" => "Joule/Mol", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KAI", "deskripsi" => "Kilogram act. ingrd.", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KD3", "deskripsi" => "Kilogram/cubic decimeter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KG", "deskripsi" => "Kilogram", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KG.", "deskripsi" => "KG.", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KGM", "deskripsi" => "Kilogram/Mol", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KGS", "deskripsi" => "Kilogram/second", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KGV", "deskripsi" => "Kilogram/cubic meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KIK", "deskripsi" => "kg act.ingrd. / kg", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KJK", "deskripsi" => "Kilojoule/kilogram", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KJM", "deskripsi" => "Kilojoule/Mol", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KM", "deskripsi" => "Kilometer", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KM2", "deskripsi" => "Square kilometer", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KMH", "deskripsi" => "Kilometer/hour", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KMN", "deskripsi" => "Kelvin/Minute", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KMS", "deskripsi" => "Kelvin/Second", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KPA", "deskripsi" => "Kilopascal", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KT", "deskripsi" => "Kilotonne", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "KVA", "deskripsi" => "Kilovoltampere", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "L", "deskripsi" => "Liter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "LB", "deskripsi" => "US pound", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "LBR", "deskripsi" => "Lembar", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "LBS", "deskripsi" => "LBS", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "LHK", "deskripsi" => "Liter per 100 km", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "LMI", "deskripsi" => "Liter/Minute", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "LMS", "deskripsi" => "Liter/Molsecond", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "LPH", "deskripsi" => "Liter per hour", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "M", "deskripsi" => "Meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "M-2", "deskripsi" => "1 / square meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "M/H", "deskripsi" => "Meter/Hour", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "M/L", "deskripsi" => "Mol per liter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "M/M", "deskripsi" => "Mol per cubic meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "M/S", "deskripsi" => "Meter/second", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "M2", "deskripsi" => "Square meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "M2S", "deskripsi" => "Square meter/second", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "M3", "deskripsi" => "Cubic meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "M3H", "deskripsi" => "Cubic meter/Hour", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "M3S", "deskripsi" => "Cubic meter/second", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MEJ", "deskripsi" => "Megajoule", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MG", "deskripsi" => "Milligram", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MGL", "deskripsi" => "Milligram/liter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MGO", "deskripsi" => "Megohm", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MGQ", "deskripsi" => "Milligram/cubic meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MHV", "deskripsi" => "Megavolt", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MI", "deskripsi" => "Mile", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MI2", "deskripsi" => "Square mile", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MIN", "deskripsi" => "Minute", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MIS", "deskripsi" => "Microsecond", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ML", "deskripsi" => "Milliliter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MLI", "deskripsi" => "Milliliter act. ingr.", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MM", "deskripsi" => "Millimeter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MM2", "deskripsi" => "Square millimeter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MM3", "deskripsi" => "Cubic millimeter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MN", "deskripsi" => "Meganewton", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MNM", "deskripsi" => "Millinewton/meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MON", "deskripsi" => "Months", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MPG", "deskripsi" => "Miles per gallon (US)", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MPL", "deskripsi" => "Millimol per liter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MPS", "deskripsi" => "Millipascal seconds", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MS2", "deskripsi" => "Meter/second squared", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MSC", "deskripsi" => "Microsiemens per centimeter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MSE", "deskripsi" => "Millisecond", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MVA", "deskripsi" => "Megavoltampere", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "MWH", "deskripsi" => "Megawatt hour", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "NA", "deskripsi" => "Nanoampere", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "NAM", "deskripsi" => "Nanometer", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "NI", "deskripsi" => "Kilonewton", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "NM", "deskripsi" => "Newton/meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "NMM", "deskripsi" => "Newton/Square millimeter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "NS", "deskripsi" => "Nanosecond", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "OCM", "deskripsi" => "Spec. Elec. Resistance", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "OM", "deskripsi" => "Spec. Elec. Resistance", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "OZ", "deskripsi" => "Ounce", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "P", "deskripsi" => "Points", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PAA", "deskripsi" => "Pair", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PAC", "deskripsi" => "Pack", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PAI", "deskripsi" => "PAIL", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PAL", "deskripsi" => "Pallet", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PAS", "deskripsi" => "Pascal second", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PCS", "deskripsi" => "PCS", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PMI", "deskripsi" => "1/minute", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PPB", "deskripsi" => "Parts per billion", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PPM", "deskripsi" => "Parts per million", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PPT", "deskripsi" => "Parts per trillion", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PRC", "deskripsi" => "Group proportion", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PRS", "deskripsi" => "Number of Persons", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PS", "deskripsi" => "Picosecond", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "PT", "deskripsi" => "Pint, US liquid", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "QML", "deskripsi" => "Kilomol", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "QT", "deskripsi" => "Quart, US liquid", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "R-U", "deskripsi" => "Nanofarad", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "RF", "deskripsi" => "Millifarad", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "RHO", "deskripsi" => "Gram/cubic centimeter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ROL", "deskripsi" => "Role", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "SET", "deskripsi" => "set", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ST", "deskripsi" => "items", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "TO", "deskripsi" => "Tonne", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "TOM", "deskripsi" => "Ton/Cubic meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "TON", "deskripsi" => "US ton", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "TS", "deskripsi" => "Thousands", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "TUB", "deskripsi" => "Tube", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "UNT", "deskripsi" => "Unit", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "VAL", "deskripsi" => "Value-only material", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "VAM", "deskripsi" => "Voltampere", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "WK", "deskripsi" => "Weeks", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "WKY", "deskripsi" => "Evaporation Rate", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "WMK", "deskripsi" => "Heat Conductivity", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "YD", "deskripsi" => "Yards", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "YD2", "deskripsi" => "Square Yard", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "YD3", "deskripsi" => "Cubic yard", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "YR", "deskripsi" => "Years", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "ZAK", "deskripsi" => "ZAK", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "µA", "deskripsi" => "Microampere", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "µF", "deskripsi" => "Microfarad", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "µGL", "deskripsi" => "Microgram/liter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "µGQ", "deskripsi" => "Microgram/cubic meter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "µL", "deskripsi" => "Microliter", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1],
            ["kode" => "µM", "deskripsi" => "Micrometer", "tipe" => "BUNIT", "created_by" => 1, "updated_by" => 1]
        ]);

        DB::table('master_options')->insert([
            ["kode" => "10101", "deskripsi" => "Kapas", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10102", "deskripsi" => "Serat Rayon", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10103", "deskripsi" => "Kapas Kontaminasi", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10199", "deskripsi" => "Waste Kapas", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10201", "deskripsi" => "Chemicals", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10302", "deskripsi" => "Benang Spinning", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10303", "deskripsi" => "Benang", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10304", "deskripsi" => "Benang Jahit", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10399", "deskripsi" => "Waste Benang", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10406", "deskripsi" => "Kain", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10499", "deskripsi" => "Waste Kain", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10507", "deskripsi" => "Dacron/Hollow", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10601", "deskripsi" => "Packaging", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10702", "deskripsi" => "Accesorries", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10801", "deskripsi" => "Spare parts", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10901", "deskripsi" => "Tools", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "10902", "deskripsi" => "Asset", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "11002", "deskripsi" => "Utility", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "11103", "deskripsi" => "Oils & Lubricants Gr", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "11204", "deskripsi" => "Bahan Bakar", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "11305", "deskripsi" => "Umum", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "11406", "deskripsi" => "Marketing", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "11501", "deskripsi" => "TKA Rutin", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "11502", "deskripsi" => "TKA Mesin Baru", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "11503", "deskripsi" => "TKA Mesin Lama", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "19907", "deskripsi" => "Services", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20101", "deskripsi" => "Wash towel", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020101M", "deskripsi" => "Wash towel - Mass Or Wash towel - Mass Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020101S", "deskripsi" => "Wash towel - Spec Or Wash towel - Special Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20102", "deskripsi" => "Face Towel", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020102M", "deskripsi" => "Face Towel - Mass Or Face Towel - Mass Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020102S", "deskripsi" => "Face Towel - Spec Or Face Towel - Special Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20103", "deskripsi" => "Sport Towel", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020103M", "deskripsi" => "Sport Towel - Mass O Sport Towel - Mass Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020103S", "deskripsi" => "Sport Towel - SpecOr Sport Towel - Special Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20104", "deskripsi" => "Travel Towel", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020104M", "deskripsi" => "Travel Towel - MassO Travel Towel - Mass Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020104S", "deskripsi" => "Travel Towel - SpecO Travel Towel - Special Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20105", "deskripsi" => "Medium Towel", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020105M", "deskripsi" => "Medium Towel - MassO Medium Towel - Mass Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020105S", "deskripsi" => "Medium Towel - SpecO Medium Towel - Special Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20106", "deskripsi" => "Bath Towel", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020106M", "deskripsi" => "Bath Towel - MassOrd Bath Towel - Mass Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020106S", "deskripsi" => "Bath Towel - SpecOrd Bath Towel - Special Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20107", "deskripsi" => "Pool Towel", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020107M", "deskripsi" => "Pool Towel - Mass Or Pool Towel - Mass Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020107S", "deskripsi" => "Pool Towel - SpecOrd Pool Towel - Special Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20108", "deskripsi" => "Bath Mat", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020108M", "deskripsi" => "Bath Mat - Mass Ord\ Bath Mat - Mass Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020108S", "deskripsi" => "Bath Mat - Spec Ord Bath Mat - Special Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20109", "deskripsi" => "Bath Robe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020109M", "deskripsi" => "Bath Robe - Mass Ord Bath Robe - Mass Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020109S", "deskripsi" => "Bath Robe - Spec. Or Bath Robe - Special Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20110", "deskripsi" => "Others", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20111", "deskripsi" => "Towels in Kg", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20198", "deskripsi" => "Towel SET", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020198M", "deskripsi" => "Towel SET - Mass Ord Towel SET - Mass Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "020198S", "deskripsi" => "Towel SET - Mass Ord Towel SET - Special Order", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20199", "deskripsi" => "Waste Towel", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20201", "deskripsi" => "Men", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20202", "deskripsi" => "Lady", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20203", "deskripsi" => "Boys", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20204", "deskripsi" => "Girls", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20299", "deskripsi" => "Waste Garment", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20301", "deskripsi" => "Bantal & Guling", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20302", "deskripsi" => "Sprei & Bed Cover", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "20303", "deskripsi" => "Other Beding Product", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30001", "deskripsi" => "Eks.Pick Up (Antar)", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30002", "deskripsi" => "Eks.Retur", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30003", "deskripsi" => "Eks.Replace ex Retur", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30101", "deskripsi" => "MC-IM-IDR-Jasa", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30102", "deskripsi" => "MC-IM-IDR-Trucking", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30103", "deskripsi" => "MC-IM-IDR-Penumpukan", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30104", "deskripsi" => "MC-IM-IDR-Lift on", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30105", "deskripsi" => "MC-IM-IDR-lift off", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30106", "deskripsi" => "AC-IM-IDR-Doc Plyran", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30107", "deskripsi" => "AC-IM-IDR-Bea Mtr", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30108", "deskripsi" => "AC-IM-IDR-Chg-D-PPJK", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30109", "deskripsi" => "AC-IM-IDR-OB charge", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30110", "deskripsi" => "AC-IM-IDR-Extra Chg", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30111", "deskripsi" => "AC-IM-IDR-SPJM Chg", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30112", "deskripsi" => "AC-IM-IDR-HICO Scan", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30113", "deskripsi" => "AC-IM-IDR-SPJK", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30114", "deskripsi" => "AC-IM-IDR-Adm Plyran", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30115", "deskripsi" => "AC-IM-IDR-Prep PIB", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30116", "deskripsi" => "AC-IM-IDR-Adm Bank", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30117", "deskripsi" => "MC-EX-IDR-hdl_jsa fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30118", "deskripsi" => "MC-EX-IDR-trck fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30119", "deskripsi" => "MC-EX-IDR-Lf on chg", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30120", "deskripsi" => "MC-EX-IDR-str_Loff C", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30121", "deskripsi" => "MC-EX-IDR-adm bank", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30122", "deskripsi" => "MC-EX-IDR-seal Fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30123", "deskripsi" => "MC-EX-IDR-Mtri Chrg", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30124", "deskripsi" => "AC-EX-IDR-repo cost", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30125", "deskripsi" => "AC-EX-IDR-PEB fee", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30126", "deskripsi" => "AC-EX-IDR-adm fee", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30127", "deskripsi" => "AC-EX-IDR-ext_cls Fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30128", "deskripsi" => "AC-EX-IDR-Ovst_tr Fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30129", "deskripsi" => "AC-EX-IDR-others cst", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30201", "deskripsi" => "MC-IM-USD-THC", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30202", "deskripsi" => "MC-IM-USD-CFS", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30203", "deskripsi" => "AC-IM-USD-Demurrage", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30204", "deskripsi" => "AC-IM-USD-Doc Fee", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30205", "deskripsi" => "AC-IM-USD-Agency Fee", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30206", "deskripsi" => "AC-IM-USD-Repair", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30207", "deskripsi" => "AC-IM-USD-Imp Srcv", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30208", "deskripsi" => "AC-IM-USD-cleaning", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30209", "deskripsi" => "MC-EX-USD-Sea-air Fr", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30210", "deskripsi" => "MC-EX-USD-THC", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30211", "deskripsi" => "AC-EX-USD-Doc_BL Fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30212", "deskripsi" => "AC-EX-USD-amdt_BL Fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30213", "deskripsi" => "AC-EX-USD-agency Fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30214", "deskripsi" => "AC-EX-USD-adm Fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30215", "deskripsi" => "AC-EX-USD-oth cost", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30216", "deskripsi" => "MC-IM-USD-O/F", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30217", "deskripsi" => "MC-IM-IDR-THC", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30301", "deskripsi" => "MC-IM-SGD-THC", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30302", "deskripsi" => "MC-IM-SGD-CFS", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30303", "deskripsi" => "AC-IM-SGD-Demurrage", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30304", "deskripsi" => "AC-IM-SGD-Doc Fee", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30305", "deskripsi" => "AC-IM-SGD-Agency Fee", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30306", "deskripsi" => "AC-IM-SGD-Repair", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30307", "deskripsi" => "AC-IM-SGD-Imp Srcv", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30308", "deskripsi" => "AC-IM-SGD-cleaning", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30309", "deskripsi" => "MC-EX-SGD-Sea-air Fr", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30310", "deskripsi" => "MC-EX-SGD-THC", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30311", "deskripsi" => "AC-EX-SGD-Doc_BL Fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30312", "deskripsi" => "AC-EX-SGD-amdt_BL Fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30313", "deskripsi" => "AC-EX-SGD-agency Fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30314", "deskripsi" => "AC-EX-SGD-adm Fe", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "30315", "deskripsi" => "AC-EX-SGD-oth cost", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "40101", "deskripsi" => "Kain Denim", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "41110", "deskripsi" => "BODY", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "41120", "deskripsi" => "WANGKY", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "41130", "deskripsi" => "RIB", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "41140", "deskripsi" => "MANSET", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "41150", "deskripsi" => "Kaos Tshirt", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "50101", "deskripsi" => "Bleach cotton", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "50199", "deskripsi" => "Waste bleach cotton", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "70101", "deskripsi" => "Denim", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "70102", "deskripsi" => "Woven Grey", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1],
            ["kode" => "70103", "deskripsi" => "Yarn Apac", "tipe" => "MATGROUP", "created_by" => 1, "updated_by" => 1]
        ]);

        DB::table('master_options')->insert([
            ["kode" => "3000", "deskripsi" => "Raw materials", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3001", "deskripsi" => "Bahan Pembantu", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3005", "deskripsi" => "Stationary", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3006", "deskripsi" => "Pantry", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3007", "deskripsi" => "Factory Supply", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3008", "deskripsi" => "Coal, Fuel & Gasoline", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3010", "deskripsi" => "Waste Cotton Product", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3011", "deskripsi" => "Cotton RM WIP", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3030", "deskripsi" => "Operating supplies", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3040", "deskripsi" => "Spare parts", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3050", "deskripsi" => "Packaging and empties", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3060", "deskripsi" => "Stationary", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3070", "deskripsi" => "Chemical & Lubricants", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3080", "deskripsi" => "OIL", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3100", "deskripsi" => "Trading goods", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3200", "deskripsi" => "Services", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "3300", "deskripsi" => "Nonvaluated material", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "7900", "deskripsi" => "Semifinished products", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "7920", "deskripsi" => "Finished products", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "7921", "deskripsi" => "Finished products SF", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "7922", "deskripsi" => "Raw Materials Hasil Prd.", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1],
            ["kode" => "7923", "deskripsi" => "Finished products (Beli)", "tipe" => "VALCL", "created_by" => 1, "updated_by" => 1]
        ]);
    }
}
